spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  # thymeleaf start
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
# thymeleaf end